spring.application.name=budget-predict-api

# PostgreSQL database connection configuration
spring.datasource.url=jdbc:postgresql://ep-winter-cake-at6g31jc.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=YOUR_DATABASE_PASSWORD
spring.datasource.driverClassName=org.postgresql.Driver

# JPA/Hibernate parameters
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Embedded Tomcat Server Port
server.port=8080

# Groq LLM API Key
groq.api.key=YOUR_GROQ_API_KEY
